services:
  api:
    build: .
    container_name: metronomdeul-api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=mongodb://mongo:27017
      - DATABASE_NAME=metronomdeul
      - ALLOWED_ORIGIN=http://localhost:5173 
      - JWT_SECRET=devsecret
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:8
    container_name: metronomdeul-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:


